name: Unzip LMS
on: [push, workflow_dispatch]

jobs:
  unzip-now:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Unzip file
        run: |
          if [ -f "lms-development-plan.zip" ]; then
            unzip -o lms-development-plan.zip
            rm lms-development-plan.zip
            
            git config --global user.name "GitHub Action"
            git config --global user.email "action@github.com"
            git add .
            git commit -m "Unzipped successfully"
            git push
          else
            echo "Zip file not found yet."
          fi
